Reports were not fetched properly
forest-watcher/forest-watcher-desktop pull request #26
Opened 2017-07-05 10:54 UTC by Bluesmile82

This should fix the fetching of the new reports into the reports page:
The reports were not checking the index provided by the url. Also changed the update of the page to fetch also when the url changes.

2017-07-06 16:32 UTC, edbrett commented
Updates have been made. Please review. 👓

2017-07-07 11:00 UTC, j8seangel requested changes
Please review the report filter by template bug.
Also, I think we should change the text of the notifications when there isn't any response because it shows `Unable to load reports` and we did correctly but they are empty.

2017-07-07 11:00 UTC, j8seangel commented on src/components/pages/reports/ReportsContainer.js
> +const getTemplateOptions = (templates) => {
Why don't do that on the `ReportsFiltersContainer` directly?
I mean we are doing in this container and then pass as props to the ReportsFilter component.
Also let you know that the filter is not being populate correctly 
![image](https://user-images.githubusercontent.com/10500650/27955197-f7dd3b4e-6313-11e7-9143-9573cb981f53.png)

2017-07-07 11:52 UTC, edbrett commented
i18n string for no results in selectors added.

2017-07-07 12:37 UTC, merged