Feature/contextual layers
forest-watcher/forest-watcher-desktop pull request #30
Opened 2017-07-11 20:58 UTC by Bluesmile82

- [ ] Add map with layers preview
- [ ] Select and add GFW layers
- [ ] Add custom layers
- [ ] Display the layers in the area map?

2017-07-13 12:26 UTC, edbrett requested changes
Some comments for you. Also getting lots of bugs with selecting, deselecting, adding layers in general.

2017-07-13 12:26 UTC, edbrett commented on src/components/map/Map.js
> +      if (!this.map.hasLayer(layer)) layer.addTo(this.map);
I know we aren't building the map now, but I think this should follow the pattern of all the other map parts be held in its own component. You can pass this.map up to the top level like in areas manage and pass the layers around that way.

2017-07-13 12:26 UTC, edbrett commented on src/components/pages/settings/LayersManager.js
> +    this.state = {
This should be at top level comp only.

2017-07-13 12:26 UTC, edbrett commented on src/modules/layers.js
> +export function getGFWLayers() {
For the sake of completeness, should we have some loading state here like other fetches? Might be useful when rendering the form and setting loaders etc.

2017-07-13 12:26 UTC, edbrett commented on src/modules/layers.js
> +export function createLayer(layer, teamId) {
Definitely need a loading prop action here.

2017-07-13 12:26 UTC, edbrett commented on src/modules/layers.js
> +export function getLayers() {
And here

2017-07-13 12:26 UTC, edbrett commented on src/styles/_react-switch-button.scss
> +/**
Are these custom styles or from the npm module?

2017-07-13 12:26 UTC, edbrett commented on src/styles/components/_c-map.scss
> +  &.-layers-container {
Not sure about this. Should be its own independant component placed separately. Like zoom controls etc.

2017-07-14 08:39 UTC, Bluesmile82 commented on src/styles/_react-switch-button.scss
> +/**
They are custom. Copied from the module

2017-07-14 10:47 UTC, closed without merging

2017-07-14 10:47 UTC, edbrett commented
Closed as branched off by enable-layers