Feature/enable layers
forest-watcher/forest-watcher-desktop pull request #33
Opened 2017-07-13 14:48 UTC by Bluesmile82

Second Contextual-Layer PR 🏎 
(This PR contains the Feature/contextual-layers)
-[x] Add LayersSwitcher to toggle Layers visibility in the API
-[x] Add functionality for team Layers:
  - [x] Checkbox to add a team layer instead of a personal layer
  - [x] Display team layers with a label

2017-07-14 09:42 UTC, edbrett requested changes
I am still getting problems with using the layer manager in general on my machine. Lets review when you get to office together.

2017-07-14 09:42 UTC, edbrett commented on src/components/ui/Checkbox.js
> +        { typeof checked !== 'undefined' ?
Can this not go directly into the checked={} param of the input?

2017-07-14 09:42 UTC, edbrett commented on src/components/map/Map.js
> +  updateLayers(layerUrls) {
I still dont like this. this.map can easily be passed outside of the component to the Layers component and be added there. This is poluting the map component and adding complexity when it is there to be reusable. All of this code should be inside the component that manages the layers.

2017-07-14 09:42 UTC, edbrett commented on src/components/pages/settings/LayersForm.js
> +        <form onSubmit={(e) => this.addLayers(e)}>
Why not use the Form component we have been using for other forms?

2017-07-14 09:42 UTC, edbrett commented on src/components/pages/settings/LayersForm.js
> +                <div key={i}>
The key could go on the Checkbox components then you wouldn't need these divs

2017-07-14 09:42 UTC, edbrett commented on src/components/pages/settings/LayersForm.js
> +          <div>
these divs aren't needed

2017-07-14 09:42 UTC, edbrett commented on src/components/pages/settings/LayersManager.js
> +      <div className="c-layers-manager">
This is interesting, and also not particularly important, but I generally use .l-class as opposed to .c-class when something contains lots of other components. Layout classes handle positioning on the page etc, and .c-classes handle the finer details. Good to follow the same format through our projects so would be good to decide on this.

2017-07-14 09:42 UTC, edbrett commented on src/components/pages/settings/LayersFormContainer.js
> +    return {
This again is point of preference, but as there are not a lot of props, and similar things are getting passed to LayerForm and LayerSwitcher, we could have a single Container to the LayersForm (their parent), and then pass the need props to each. This leaves the Switcher and Form as UI components and you can control the state of each more clearly. Lets discuss.

2017-07-14 09:42 UTC, edbrett commented on src/components/pages/settings/LayersSwitcher.js
> +    this.props.getLayers();
Should this be called on the parent (LayersManager)?

2017-07-14 09:42 UTC, edbrett commented on src/components/pages/settings/LayersSwitcher.js
> +        <div className="title"><FormattedMessage id={"settings.selectedLayers"} /></div>
could use a h3 tag here to be more expressive.

2017-07-14 09:42 UTC, edbrett commented on src/components/pages/settings/LayersSwitcher.js
> +            <div key={i}>
Again can place these on the component to reduce code.

2017-07-14 09:42 UTC, edbrett commented on src/components/pages/settings/Settings.js
> +        <div className="l-content">
Nice work. Big reduction and simplification.

2017-07-14 09:42 UTC, edbrett commented on src/components/pages/settings/TeamsForm.js
> +                  <div>
Empty divs again. Not needed.

2017-07-14 09:42 UTC, edbrett commented on src/components/pages/settings/TeamsForm.js
> +                <div>
Here too.

2017-07-14 09:42 UTC, edbrett commented on src/components/ui/Tab.js
> +function Tab({ options, selectedIndex, handleTabIndexChange }) {
Cooooool. 😎 . Lets not forget we have this for other projects.

2017-07-14 09:42 UTC, edbrett commented on src/styles/_react-switch-button.scss
> + * React Switch Button control style.
Not a big fan of copying styles to override as often we only need to change a few classes. But if it works 👍

2017-07-14 09:42 UTC, edbrett commented on src/styles/components/_c-layers-manager.scss
> +  .section {
spacing.

2017-07-14 09:42 UTC, edbrett commented on src/styles/components/_c-map.scss
> +  &.-layers-container {
spacing

2017-07-14 09:44 UTC, edbrett commented
Also can we organise the settings pages better. There are way to many files in there and it is hard to know what are parents and what are child components.

2017-07-14 09:47 UTC, edbrett commented
Also also, I think as some of these components are starting to become larger (and manage other components) we should be diving up the functions with comments to make is clearer what is happening.

2017-07-14 10:20 UTC, edbrett commented on src/components/pages/settings/LayersSwitcher.js
> +            <div key={i}>
Sorry this is wrong. Ignore my comment

2017-07-17 14:29 UTC, Bluesmile82 commented on src/components/ui/Checkbox.js
> +        { typeof checked !== 'undefined' ?
We don't want checked to be false if the checked is not defined. We don't want it to have the param. So is still uncontrolled.

2017-07-18 10:44 UTC, edbrett commented on src/styles/_base.scss
> +h3 {
we have a texts.scss file for things like this as base should be to normalize the css.

2017-07-18 10:45 UTC, edbrett commented on src/styles/_base.scss
> +  font-weight: bold;
we have a settings file for things like bold.

2017-07-18 10:45 UTC, edbrett commented on src/styles/_base.scss
> +  font-weight: bold;
And always use number for font weights as font families etc may not do what you expect with bold.

2017-07-18 11:53 UTC, merged